version: '3'
services:
    lodex-extended:
        container_name: lodex-extended
        build:
            context: .
            args:
                - http_proxy
                - https_proxy
        image: inistcnrs/lodex-extended:6.16.0
        environment:
            - http_proxy
            - https_proxy
        ports:
            - "31976:31976"
